//w.a.p to check whether the given number is mobile number or not
number='9410546110'
console.log(number.length==10?'it is a mobile number':'it is not a mobile numaber')


//w.a.p to check the given mail id is gmail.com(@gmail.com)
mail='bettybabu075@gmail.com'
mail1=mail.endsWith('@gmail.com')
console.log(mail1?'it is a mail id':'not a mail');

//w.a.p to check a word starts with the letter q

str='question'

console.log(str.startsWith('q')||str.startsWith('Q')?'starts with q':'not starts with q');
